# Generated by Django 5.2.17 on 2026-09-22 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('food', 'Food'), ('rent', 'Rent'), ('travel', 'Travel'), ('groceries', 'Groceries'), ('fuel', 'Fuel'), ('shopping', 'Shopping'), ('medical', 'Medical'), ('education', 'Education'), ('entertaiment', 'Entertaiment'), ('investment', 'Investment'), ('others', 'Others')], max_length=100)),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
