# Generated by Django 5.2.17 on 2026-09-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dept', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
